apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://lexfrei.github.io/charts"
    targetRevision: "0.1.2"
    chart: frame
    helm:
      values: |
        image:
          repository: "redis"
          tag: "alpine"
        pvcs:
          enabled: true
          list:
            - name: redis-data
              storageClassName: "longhorn"
              accessMode: ReadWriteOnce
              size: 1Gi
              path: /data
        service:
          port: 6379
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
